name: forandar
version: 0.2.8
description: A forth implementation in Dart
author: José Luis Cruz <joseluis@andamira.net>
homepage: https://gitlab.com/andamira/forandar
dev_dependencies:
    test: '^0.12.6'
