name: forandar
version: 0.3.5
description: A Forth implementation in Dart
author: José Luis Cruz <joseluis@andamira.net>
homepage: https://github.com/andamira/forandar
dependencies:
    args: "^0.13.2"
dev_dependencies:
    benchmark_harness: '^1.0.4'
    test: '^0.12.6'
executables:
    forandar: forandar.dart
