name: forandar
version: 0.9.9
description: A Forth system implemented in Dart
author: José Luis Cruz <joseluis@andamira.net>
homepage: https://github.com/andamira/forandar
dependencies:
    args: "^0.13.4"
    browser: "^0.10.0+2"
    dart_to_js_script_rewriter: "^1.0.1"
    stack_trace: "^1.6.1"
dev_dependencies:
    test: '^0.12.6'
executables:
    forandar:
    forandar_debug:
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
    commandLineOptions:
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
