name: forandar
version: 0.8.37
description: A Forth implementation in Dart
author: José Luis Cruz <joseluis@andamira.net>
homepage: https://github.com/andamira/forandar
dependencies:
    args: "^0.13.2"
    dart_to_js_script_rewriter: "^0.1.0+4"
    yaml: "^2.1.7"
dev_dependencies:
    test: '^0.12.6'
executables:
    forandar: forandar.dart
transformers:
- dart_to_js_script_rewriter
- $dart2js:
    minify: true
    commandLineOptions:
    - --show-package-warnings
    - --trust-type-annotations
    - --trust-primitives
    - --enable-experimental-mirrors
