name: forandar
description: A forth implementation in Dart, and compiled to javascript
author: joseLuis Cruz <joseluis@andamira.net>
homepage: https://github.com/andamira/forandar
dev_dependencies:
    # test: '0.12.6' # Wait until bugfix for: https://github.com/dart-lang/sdk/issues/24112
